### ISSUE TITLE
`const String key` shouldn't be constant

### ISSUE THREAD

**Issue by bdsm-spuddy** [flash89y/Arduino#1]
I've only looked at DogColllar2, but in the .h file there's a line
```
const String key; // 'static' key - each remote has it's own
```
When compiling with `arduino-cli` this causes problems

```
DogCollar2.cpp: In constructor 'DogCollar::DogCollar(int, String, int)':
DogCollar2.cpp:33:36: error: passing 'const String' as 'this' argument of 'void String::setCharAt(unsigned int, char)' discards qualifiers [-fpermissive]
                 key.setCharAt(i,'1');
```

Obviously `key` isn't a constant, so the `const` declaration should be removed.

**Comment by flash89y** [comment]
Thank You for this note, that's obviously wrong and can't compile...
Don't know why this error was in there all the while, could swear i compiled and tested this code, hm...
Issue is fixed exactly like you said :)
